// Datos del hato de Ganadería La Piedad.
// SEED_VERSION: súbela cada vez que cambien estos datos. Los dispositivos que
// ya tienen la app instalada detectan la versión nueva y se actualizan solos
// (guardando antes un respaldo de seguridad de lo que tenían).
export const SEED_VERSION = '2026-08-09-toros';
export const SEED = {
 "vacas": [
  {
   "chapeta": "001",
   "codigo": "367-20",
   "genetica": "Plus x Plus",
   "fechaNac": "2020-02-12",
   "sexo": "Hembra",
   "ultimoParto": "2025-08-29",
   "criaActual": "Aurora",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "002",
   "codigo": "598-120",
   "genetica": "Plus",
   "fechaNac": "2020-12-20",
   "sexo": "Hembra",
   "ultimoParto": "2025-09-24",
   "criaActual": "Victoria",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "003",
   "codigo": "413-21",
   "genetica": "Plus x Plus",
   "fechaNac": "2021-04-02",
   "sexo": "Hembra",
   "ultimoParto": "2025-08-18",
   "criaActual": "Karina",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "FALLECIDA",
   "fechaSalida": "2025-03-09",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "004",
   "codigo": "838-22",
   "genetica": "Plus x Plus",
   "fechaNac": "2022-05-03",
   "sexo": "Hembra",
   "ultimoParto": "2025-08-23",
   "criaActual": "Minerva",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "005",
   "codigo": "566-3",
   "genetica": "Plus",
   "fechaNac": "2023-04-30",
   "sexo": "Hembra",
   "ultimoParto": "2025-11-29",
   "criaActual": "Azabache",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "006",
   "codigo": "235-21",
   "genetica": "Plus",
   "fechaNac": "2021-06-11",
   "sexo": "Hembra",
   "ultimoParto": "2025-10-23",
   "criaActual": "Fortuna",
   "fechaPrenez": "2026-04-29",
   "fechaProbParto": "2027-02-03",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "007",
   "codigo": "307-13",
   "genetica": "Plus x Plus",
   "fechaNac": "2023-01-04",
   "sexo": "Hembra",
   "ultimoParto": "2025-12-31",
   "criaActual": "Flora (Fallecida)",
   "fechaPrenez": "2026-03-26",
   "fechaProbParto": "2026-12-31",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "008",
   "codigo": "1076-N2",
   "genetica": "Plus",
   "fechaNac": "2022-11-03",
   "sexo": "Hembra",
   "ultimoParto": "2025-11-18",
   "criaActual": "Afrodita",
   "fechaPrenez": "2026-04-24",
   "fechaProbParto": "2027-01-29",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "009",
   "codigo": "525-3",
   "genetica": "F1",
   "fechaNac": "2023-01-06",
   "sexo": "Hembra",
   "ultimoParto": "",
   "criaActual": "",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "FALLECIDA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "010",
   "codigo": "518-2",
   "genetica": "F1",
   "fechaNac": "2022-06-19",
   "sexo": "Hembra",
   "ultimoParto": "2025-08-18",
   "criaActual": "Venus",
   "fechaPrenez": "2026-04-29",
   "fechaProbParto": "2027-02-03",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "011",
   "codigo": "310- D2",
   "genetica": "Plus x Plus",
   "fechaNac": "2022-12-28",
   "sexo": "Hembra",
   "ultimoParto": "2025-12-31",
   "criaActual": "Freya",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "012",
   "codigo": "134-3F",
   "genetica": "Plus x Plus",
   "fechaNac": "",
   "sexo": "Hembra",
   "ultimoParto": "",
   "criaActual": "",
   "fechaPrenez": "2026-02-14",
   "fechaProbParto": "2026-11-21",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "013",
   "codigo": "522-2",
   "genetica": "F1",
   "fechaNac": "2022-09-28",
   "sexo": "Hembra",
   "ultimoParto": "2025-09-25",
   "criaActual": "Iris",
   "fechaPrenez": "2026-02-14",
   "fechaProbParto": "2026-11-21",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "014",
   "codigo": "521-2",
   "genetica": "F1",
   "fechaNac": "2022-09-18",
   "sexo": "Hembra",
   "ultimoParto": "2025-09-28",
   "criaActual": "Pepa",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "015",
   "codigo": "524-2",
   "genetica": "F1",
   "fechaNac": "2022-11-03",
   "sexo": "Hembra",
   "ultimoParto": "2025-09-28",
   "criaActual": "Frida",
   "fechaPrenez": "2026-05-25",
   "fechaProbParto": "2027-03-01",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "016",
   "codigo": "414-21",
   "genetica": "Plus x Plus",
   "fechaNac": "2021-04-02",
   "sexo": "Hembra",
   "ultimoParto": "2025-10-28",
   "criaActual": "Helena",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "017",
   "codigo": "514-2",
   "genetica": "Plus",
   "fechaNac": "2022-11-03",
   "sexo": "Macho",
   "ultimoParto": "2025-11-28",
   "criaActual": "Blanquillo",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "018",
   "codigo": "775-22",
   "genetica": "Plus x Plus",
   "fechaNac": "2022-03-05",
   "sexo": "Hembra",
   "ultimoParto": "2025-08-11",
   "criaActual": "Cassandra",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "019",
   "codigo": "481-2",
   "genetica": "Plus",
   "fechaNac": "2022-06-02",
   "sexo": "Macho",
   "ultimoParto": "2025-10-11",
   "criaActual": "Colacho",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "020",
   "codigo": "138-3F",
   "genetica": "Plus x Plus",
   "fechaNac": "",
   "sexo": "Macho",
   "ultimoParto": "2025-12-18",
   "criaActual": "Júpiter",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "021",
   "codigo": "HIJ 39-3",
   "genetica": "Plus x Plus",
   "fechaNac": "",
   "sexo": "Hembra",
   "ultimoParto": "2025-12-31",
   "criaActual": "Artemisa",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "022",
   "codigo": "534-3",
   "genetica": "Plus",
   "fechaNac": "2023-02-06",
   "sexo": "Hembra",
   "ultimoParto": "2025-11-25",
   "criaActual": "India",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "023",
   "codigo": "496-2",
   "genetica": "Plus",
   "fechaNac": "2022-08-05",
   "sexo": "Macho",
   "ultimoParto": "2025-12-22",
   "criaActual": "Cerbero",
   "fechaPrenez": "2026-02-14",
   "fechaProbParto": "2026-11-21",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "024",
   "codigo": "517-2",
   "genetica": "F1",
   "fechaNac": "2022-05-22",
   "sexo": "Hembra",
   "ultimoParto": "2025-10-11",
   "criaActual": "Mónica",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "025",
   "codigo": "540-3",
   "genetica": "Plus",
   "fechaNac": "2023-02-21",
   "sexo": "Hembra",
   "ultimoParto": "2025-12-21",
   "criaActual": "Penélope",
   "fechaPrenez": "2026-02-14",
   "fechaProbParto": "2026-11-21",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "026",
   "codigo": "499",
   "genetica": "Plus x Plus",
   "fechaNac": "2022-02-18",
   "sexo": "Hembra",
   "ultimoParto": "2025-12-22",
   "criaActual": "Luna",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "027",
   "codigo": "95-112",
   "genetica": "Plus",
   "fechaNac": "2022-11-24",
   "sexo": "Macho",
   "ultimoParto": "2025-11-08",
   "criaActual": "Ulises",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "028",
   "codigo": "018-21",
   "genetica": "Plus",
   "fechaNac": "2021-02-03",
   "sexo": "Hembra",
   "ultimoParto": "2025-07-11",
   "criaActual": "Brisa (Fallecida)",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "029",
   "codigo": "512-2",
   "genetica": "Plus",
   "fechaNac": "2022-11-01",
   "sexo": "Hembra",
   "ultimoParto": "2025-11-23",
   "criaActual": "Reina",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "030",
   "codigo": "498-2",
   "genetica": "Plus",
   "fechaNac": "2022-08-06",
   "sexo": "Macho",
   "ultimoParto": "2025-11-19",
   "criaActual": "Chocolate",
   "fechaPrenez": "2026-04-29",
   "fechaProbParto": "2027-02-03",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "031",
   "codigo": "523-2",
   "genetica": "F1",
   "fechaNac": "2022-10-07",
   "sexo": "Hembra",
   "ultimoParto": "2025-10-07",
   "criaActual": "Apolo",
   "fechaPrenez": "2026-04-29",
   "fechaProbParto": "2027-02-03",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "032",
   "codigo": "527-3",
   "genetica": "F1",
   "fechaNac": "2023-01-24",
   "sexo": "Macho",
   "ultimoParto": "2025-12-23",
   "criaActual": "Palomo",
   "fechaPrenez": "2026-03-26",
   "fechaProbParto": "2026-12-31",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "033",
   "codigo": "126-3B",
   "genetica": "Plus x Plus",
   "fechaNac": "",
   "sexo": "Hembra",
   "ultimoParto": "2025-12-26",
   "criaActual": "Diana",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "034",
   "codigo": "515-2",
   "genetica": "Plus",
   "fechaNac": "2022-11-04",
   "sexo": "Macho",
   "ultimoParto": "2025-11-20",
   "criaActual": "Zeus",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "035",
   "codigo": "513-2",
   "genetica": "Plus",
   "fechaNac": "2022-11-02",
   "sexo": "Hembra",
   "ultimoParto": "2025-11-13",
   "criaActual": "Crispeta",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "036",
   "codigo": "492",
   "genetica": "Plus x Plus",
   "fechaNac": "",
   "sexo": "Hembra",
   "ultimoParto": "2026-01-25",
   "criaActual": "Maya",
   "fechaPrenez": "2026-04-25",
   "fechaProbParto": "2027-01-30",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "037",
   "codigo": "531-3 Plus",
   "genetica": "Plus",
   "fechaNac": "2023-04-30",
   "sexo": "Hembra",
   "ultimoParto": "2025-11-28",
   "criaActual": "Patty",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "038",
   "codigo": "363-20",
   "genetica": "Plus x Plus",
   "fechaNac": "2020-01-12",
   "sexo": "Hembra",
   "ultimoParto": "2025-11-04",
   "criaActual": "Alma",
   "fechaPrenez": "2026-04-28",
   "fechaProbParto": "2027-02-02",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "039",
   "codigo": "0264-22",
   "genetica": "Plus x Plus",
   "fechaNac": "2022-12-28",
   "sexo": "Hembra",
   "ultimoParto": "2025-11-05",
   "criaActual": "Calista",
   "fechaPrenez": "2026-04-26",
   "fechaProbParto": "2027-01-31",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "040",
   "codigo": "376-20",
   "genetica": "Plus",
   "fechaNac": "2020-07-06",
   "sexo": "Macho",
   "ultimoParto": "2025-08-01",
   "criaActual": "Augusto",
   "fechaPrenez": "2026-05-20",
   "fechaProbParto": "2027-02-24",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "041",
   "codigo": "531-3 F1",
   "genetica": "F1",
   "fechaNac": "2023-05-15",
   "sexo": "Macho",
   "ultimoParto": "2025-07-17",
   "criaActual": "Julio",
   "fechaPrenez": "2025-11-30",
   "fechaProbParto": "2026-09-06",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "042",
   "codigo": "69-920",
   "genetica": "Convencional",
   "fechaNac": "",
   "sexo": "Macho",
   "ultimoParto": "2025-11-06",
   "criaActual": "Marcos",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "043",
   "codigo": "82x-45",
   "genetica": "Convencional",
   "fechaNac": "",
   "sexo": "Macho",
   "ultimoParto": "2025-05-27",
   "criaActual": "Carbón",
   "fechaPrenez": "2025-11-30",
   "fechaProbParto": "2026-09-06",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "044",
   "codigo": "780",
   "genetica": "Convencional",
   "fechaNac": "",
   "sexo": "Hembra",
   "ultimoParto": "2025-06-12",
   "criaActual": "Lolita",
   "fechaPrenez": "2026-02-14",
   "fechaProbParto": "2026-11-21",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "045",
   "codigo": "536",
   "genetica": "F1",
   "fechaNac": "",
   "sexo": "Hembra",
   "ultimoParto": "2026-01-24",
   "criaActual": "Odín",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "046",
   "codigo": "564",
   "genetica": "F1",
   "fechaNac": "",
   "sexo": "Hembra",
   "ultimoParto": "2026-01-19",
   "criaActual": "Mercurio",
   "fechaPrenez": "2026-04-29",
   "fechaProbParto": "2027-02-03",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "047",
   "codigo": "534",
   "genetica": "F1",
   "fechaNac": "",
   "sexo": "Hembra",
   "ultimoParto": "2026-03-17",
   "criaActual": "Cría fallecida",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "048",
   "codigo": "573",
   "genetica": "F1",
   "fechaNac": "",
   "sexo": "Hembra",
   "ultimoParto": "2026-03-15",
   "criaActual": "Cría fallecida",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "049",
   "codigo": "537",
   "genetica": "F1",
   "fechaNac": "",
   "sexo": "Hembra",
   "ultimoParto": "2026-02-24",
   "criaActual": "Bambú",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "050",
   "codigo": "2366",
   "genetica": "F1",
   "fechaNac": "",
   "sexo": "Hembra",
   "ultimoParto": "2026-02-26",
   "criaActual": "Capuchino",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "051",
   "codigo": "537",
   "genetica": "F1",
   "fechaNac": "",
   "sexo": "Hembra",
   "ultimoParto": "2026-05-05",
   "criaActual": "Cría vendida",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "052",
   "codigo": "2366",
   "genetica": "F1",
   "fechaNac": "",
   "sexo": "Hembra",
   "ultimoParto": "2026-07-03",
   "criaActual": "Princesa",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "053",
   "codigo": "2367",
   "genetica": "F1",
   "fechaNac": "",
   "sexo": "Hembra",
   "ultimoParto": "2026-05-20",
   "criaActual": "Cría fallecida",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "054",
   "codigo": "1C",
   "genetica": "F1",
   "fechaNac": "",
   "sexo": "Hembra",
   "ultimoParto": "",
   "criaActual": "",
   "fechaPrenez": "2026-05-17",
   "fechaProbParto": "2027-02-21",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "055",
   "codigo": "055-3",
   "genetica": "Plus x Plus",
   "fechaNac": "",
   "sexo": "Hembra",
   "ultimoParto": "",
   "criaActual": "",
   "fechaPrenez": "2026-05-26",
   "fechaProbParto": "2027-03-02",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "5.º viaje",
   "tipo": "vaca"
  },
  {
   "chapeta": "056",
   "codigo": "052-3",
   "genetica": "Plus x Plus",
   "fechaNac": "",
   "sexo": "Hembra",
   "ultimoParto": "",
   "criaActual": "",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "5.º viaje",
   "tipo": "vaca"
  },
  {
   "chapeta": "057",
   "codigo": "139",
   "genetica": "Plus x Plus",
   "fechaNac": "",
   "sexo": "Hembra",
   "ultimoParto": "2026-05-22",
   "criaActual": "Jennifer",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "5.º viaje",
   "tipo": "vaca"
  },
  {
   "chapeta": "058",
   "codigo": "1327",
   "genetica": "Plus x Plus",
   "fechaNac": "",
   "sexo": "Hembra",
   "ultimoParto": "",
   "criaActual": "",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "059",
   "codigo": "1072",
   "genetica": "Plus x Plus",
   "fechaNac": "",
   "sexo": "Hembra",
   "ultimoParto": "",
   "criaActual": "",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "060",
   "codigo": "1341",
   "genetica": "Plus x Plus",
   "fechaNac": "",
   "sexo": "Hembra",
   "ultimoParto": "",
   "criaActual": "",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "",
   "tipo": "vaca"
  },
  {
   "chapeta": "Eclipse",
   "codigo": "",
   "genetica": "",
   "fechaNac": "2023-01-02",
   "sexo": "Macho",
   "ultimoParto": "",
   "criaActual": "",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "Toro reproductor",
   "tipo": "toro"
  },
  {
   "chapeta": "Timoteo",
   "codigo": "",
   "genetica": "",
   "fechaNac": "2023-03-17",
   "sexo": "Macho",
   "ultimoParto": "",
   "criaActual": "",
   "fechaPrenez": "",
   "fechaProbParto": "",
   "estado": "ACTIVA",
   "fechaSalida": "",
   "notas": "Toro reproductor",
   "tipo": "toro"
  }
 ],
 "terneros": [
  {
   "nombre": "Carbón",
   "sexo": "Macho",
   "fechaNac": "2025-05-27",
   "codigoMadre": "043",
   "activo": false,
   "fechaSalida": "2026-06-01",
   "tipoSalida": "FALLECIDO",
   "brucelosis": "Sí",
   "observaciones": "",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Marcos",
   "sexo": "Macho",
   "fechaNac": "2025-06-11",
   "codigoMadre": "042",
   "activo": false,
   "fechaSalida": "",
   "tipoSalida": "FALLECIDO",
   "brucelosis": "Sí",
   "observaciones": "",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Lolita",
   "sexo": "Hembra",
   "fechaNac": "2025-06-12",
   "codigoMadre": "044",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "Sí",
   "observaciones": "",
   "ultimoPeso": 154.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Julio",
   "sexo": "Macho",
   "fechaNac": "2025-07-17",
   "codigoMadre": "041",
   "activo": false,
   "fechaSalida": "2026-03-31",
   "tipoSalida": "VENDIDO",
   "brucelosis": "Sí",
   "observaciones": "",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Augusto",
   "sexo": "Macho",
   "fechaNac": "2025-08-01",
   "codigoMadre": "040",
   "activo": false,
   "fechaSalida": "2026-03-31",
   "tipoSalida": "VENDIDO",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Karina",
   "sexo": "Hembra",
   "fechaNac": "2025-08-18",
   "codigoMadre": "003",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": 141.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Venus",
   "sexo": "Hembra",
   "fechaNac": "2025-08-18",
   "codigoMadre": "010",
   "activo": false,
   "fechaSalida": "2025-11-05",
   "tipoSalida": "VENDIDO",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Minerva",
   "sexo": "Hembra",
   "fechaNac": "2025-08-23",
   "codigoMadre": "004",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": 124.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Aurora",
   "sexo": "Hembra",
   "fechaNac": "2025-08-29",
   "codigoMadre": "001",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": 157.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Victoria",
   "sexo": "Hembra",
   "fechaNac": "2025-09-24",
   "codigoMadre": "002",
   "activo": false,
   "fechaSalida": "2026-04-10",
   "tipoSalida": "FALLECIDO",
   "brucelosis": "No",
   "observaciones": "Fallecido: Enfermedad",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Iris",
   "sexo": "Hembra",
   "fechaNac": "2025-09-25",
   "codigoMadre": "013",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": 93.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Frida",
   "sexo": "Hembra",
   "fechaNac": "2025-09-28",
   "codigoMadre": "015",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": 78.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Apolo",
   "sexo": "Macho",
   "fechaNac": "2025-10-07",
   "codigoMadre": "031",
   "activo": false,
   "fechaSalida": "2026-03-31",
   "tipoSalida": "VENDIDO",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Pepa",
   "sexo": "Hembra",
   "fechaNac": "2025-10-08",
   "codigoMadre": "014",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": 102.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Fortuna",
   "sexo": "Hembra",
   "fechaNac": "2025-10-23",
   "codigoMadre": "006",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": 105.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Helena",
   "sexo": "Hembra",
   "fechaNac": "2025-10-28",
   "codigoMadre": "016",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": 117.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Alma",
   "sexo": "Hembra",
   "fechaNac": "2025-11-04",
   "codigoMadre": "038",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": 116.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Calista",
   "sexo": "Hembra",
   "fechaNac": "2025-11-05",
   "codigoMadre": "039",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": 113.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Brisa",
   "sexo": "Hembra",
   "fechaNac": "2025-11-07",
   "codigoMadre": "028",
   "activo": false,
   "fechaSalida": "2026-05-20",
   "tipoSalida": "FALLECIDO",
   "brucelosis": "No",
   "observaciones": "Fallecida el 20/05/2026",
   "ultimoPeso": 127.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Ulises",
   "sexo": "Macho",
   "fechaNac": "2025-11-08",
   "codigoMadre": "027",
   "activo": false,
   "fechaSalida": "2026-03-31",
   "tipoSalida": "VENDIDO",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Cassandra",
   "sexo": "Hembra",
   "fechaNac": "2025-11-08",
   "codigoMadre": "018",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Colacho",
   "sexo": "Macho",
   "fechaNac": "2025-11-10",
   "codigoMadre": "019",
   "activo": false,
   "fechaSalida": "2026-03-31",
   "tipoSalida": "VENDIDO",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Monica",
   "sexo": "Hembra",
   "fechaNac": "2025-11-10",
   "codigoMadre": "024",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": 110.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Crispeta",
   "sexo": "Hembra",
   "fechaNac": "2025-11-13",
   "codigoMadre": "035",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Afrodita",
   "sexo": "Hembra",
   "fechaNac": "2025-11-18",
   "codigoMadre": "008",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": 87.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Chocolate",
   "sexo": "Macho",
   "fechaNac": "2025-11-19",
   "codigoMadre": "030",
   "activo": false,
   "fechaSalida": "2026-03-31",
   "tipoSalida": "VENDIDO",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Zeus",
   "sexo": "Macho",
   "fechaNac": "2025-11-20",
   "codigoMadre": "034",
   "activo": false,
   "fechaSalida": "2026-03-31",
   "tipoSalida": "VENDIDO",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Reina",
   "sexo": "Hembra",
   "fechaNac": "2025-11-23",
   "codigoMadre": "029",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": 111.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "India",
   "sexo": "Hembra",
   "fechaNac": "2025-11-25",
   "codigoMadre": "022",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": 97.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Paty",
   "sexo": "Hembra",
   "fechaNac": "2025-11-28",
   "codigoMadre": "037",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": 123.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Blanquillo",
   "sexo": "Macho",
   "fechaNac": "2025-11-28",
   "codigoMadre": "017",
   "activo": false,
   "fechaSalida": "",
   "tipoSalida": "FALLECIDO",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Azabache",
   "sexo": "Macho",
   "fechaNac": "2025-11-29",
   "codigoMadre": "005",
   "activo": false,
   "fechaSalida": "2026-03-31",
   "tipoSalida": "VENDIDO",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Jupiter",
   "sexo": "Macho",
   "fechaNac": "2025-12-18",
   "codigoMadre": "020",
   "activo": false,
   "fechaSalida": "2026-03-31",
   "tipoSalida": "VENDIDO",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Penélope",
   "sexo": "Hembra",
   "fechaNac": "2025-12-21",
   "codigoMadre": "025",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": 72.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Luna",
   "sexo": "Hembra",
   "fechaNac": "2025-12-22",
   "codigoMadre": "026",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": 86.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Cerbero",
   "sexo": "Macho",
   "fechaNac": "2025-12-22",
   "codigoMadre": "023",
   "activo": false,
   "fechaSalida": "2026-03-31",
   "tipoSalida": "VENDIDO",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Palomo",
   "sexo": "Macho",
   "fechaNac": "2025-12-23",
   "codigoMadre": "032",
   "activo": false,
   "fechaSalida": "2026-03-31",
   "tipoSalida": "VENDIDO",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Diana",
   "sexo": "Hembra",
   "fechaNac": "2025-12-26",
   "codigoMadre": "033",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": 94.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Artemisa",
   "sexo": "Hembra",
   "fechaNac": "2025-12-31",
   "codigoMadre": "021",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": 90.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Flora",
   "sexo": "Hembra",
   "fechaNac": "2025-12-31",
   "codigoMadre": "007",
   "activo": false,
   "fechaSalida": "2026-03-15",
   "tipoSalida": "FALLECIDO",
   "brucelosis": "No",
   "observaciones": "Fallecida en marzo 2026 (fecha aproximada)",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Freya",
   "sexo": "Hembra",
   "fechaNac": "2025-12-31",
   "codigoMadre": "011",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": 87.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Maya",
   "sexo": "Hembra",
   "fechaNac": "2026-01-25",
   "codigoMadre": "036",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": 57.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Mercurio",
   "sexo": "Macho",
   "fechaNac": "2026-01-19",
   "codigoMadre": "046",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": 58.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Odín",
   "sexo": "Macho",
   "fechaNac": "2026-01-24",
   "codigoMadre": "045",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "",
   "ultimoPeso": 52.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Bambi",
   "sexo": "Macho",
   "fechaNac": "2026-02-24",
   "codigoMadre": "049",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "Sí",
   "observaciones": "",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Capuchino",
   "sexo": "Macho",
   "fechaNac": "2026-02-26",
   "codigoMadre": "050",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "Sí",
   "observaciones": "",
   "ultimoPeso": 43.0,
   "fechaUltimoPesaje": "2026-04-03",
   "genetica": ""
  },
  {
   "nombre": "Abril",
   "sexo": "Hembra",
   "fechaNac": "2026-04-25",
   "codigoMadre": "054",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "Nacido del parto de vaca 54",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Vendido",
   "sexo": "Macho",
   "fechaNac": "2026-05-05",
   "codigoMadre": "051",
   "activo": false,
   "fechaSalida": "2026-05-05",
   "tipoSalida": "VENDIDO",
   "brucelosis": "No",
   "observaciones": "Macho, vendido al nacer a Ganadero Munar",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Jennifer",
   "sexo": "Hembra",
   "fechaNac": "2026-05-22",
   "codigoMadre": "057",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "⭐ Primera Gyr Pura nacida en Ganadería La Piedad. Nacida del parto de vaca 057.",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": "Gyr Pura"
  },
  {
   "nombre": "Cría 047 (murió)",
   "sexo": "",
   "fechaNac": "2026-03-17",
   "codigoMadre": "047",
   "activo": false,
   "fechaSalida": "2026-03-17",
   "tipoSalida": "FALLECIDO",
   "brucelosis": "No",
   "observaciones": "Nació enfermo, falleció",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Cría 048 (murió)",
   "sexo": "",
   "fechaNac": "2026-03-15",
   "codigoMadre": "048",
   "activo": false,
   "fechaSalida": "2026-03-15",
   "tipoSalida": "FALLECIDO",
   "brucelosis": "No",
   "observaciones": "Nació enfermo, falleció",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Cría 053 (murió)",
   "sexo": "",
   "fechaNac": "2026-05-20",
   "codigoMadre": "053",
   "activo": false,
   "fechaSalida": "2026-05-20",
   "tipoSalida": "FALLECIDO",
   "brucelosis": "No",
   "observaciones": "Ternero muerto",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  },
  {
   "nombre": "Princesa",
   "sexo": "Hembra",
   "fechaNac": "2026-07-03",
   "codigoMadre": "052",
   "activo": true,
   "fechaSalida": "",
   "tipoSalida": "",
   "brucelosis": "No",
   "observaciones": "Nacida del parto de vaca 052",
   "ultimoPeso": null,
   "fechaUltimoPesaje": "",
   "genetica": ""
  }
 ],
 "servicios": [
  {
   "tipo": "TE",
   "chapeta": "042",
   "cria": "",
   "material": "Embrión sexado",
   "raza": "",
   "fecha": "2026-07-17",
   "resultado": "PENDIENTE",
   "fechaConfirmacion": ""
  },
  {
   "tipo": "TE",
   "chapeta": "022",
   "cria": "",
   "material": "Embrión sexado",
   "raza": "",
   "fecha": "2026-07-17",
   "resultado": "PENDIENTE",
   "fechaConfirmacion": ""
  },
  {
   "tipo": "TE",
   "chapeta": "035",
   "cria": "",
   "material": "Embrión sexado",
   "raza": "",
   "fecha": "2026-07-17",
   "resultado": "PENDIENTE",
   "fechaConfirmacion": ""
  },
  {
   "tipo": "TE",
   "chapeta": "060",
   "cria": "",
   "material": "Embrión sexado",
   "raza": "",
   "fecha": "2026-07-17",
   "resultado": "PENDIENTE",
   "fechaConfirmacion": ""
  },
  {
   "tipo": "TE",
   "chapeta": "057",
   "cria": "",
   "material": "Embrión sexado",
   "raza": "",
   "fecha": "2026-07-17",
   "resultado": "PENDIENTE",
   "fechaConfirmacion": ""
  },
  {
   "tipo": "MN",
   "chapeta": "017",
   "cria": "",
   "material": "Estro Zoo + monta natural",
   "raza": "Eclipse y Timoteo",
   "fecha": "2026-08-06",
   "resultado": "PENDIENTE",
   "fechaConfirmacion": ""
  },
  {
   "tipo": "MN",
   "chapeta": "014",
   "cria": "",
   "material": "Estro Zoo + monta natural",
   "raza": "Eclipse y Timoteo",
   "fecha": "2026-08-06",
   "resultado": "PENDIENTE",
   "fechaConfirmacion": ""
  },
  {
   "tipo": "MN",
   "chapeta": "037",
   "cria": "",
   "material": "Estro Zoo + monta natural",
   "raza": "Eclipse y Timoteo",
   "fecha": "2026-08-06",
   "resultado": "PENDIENTE",
   "fechaConfirmacion": ""
  },
  {
   "tipo": "MN",
   "chapeta": "018",
   "cria": "",
   "material": "Estro Zoo + monta natural",
   "raza": "Eclipse y Timoteo",
   "fecha": "2026-08-06",
   "resultado": "PENDIENTE",
   "fechaConfirmacion": ""
  },
  {
   "tipo": "MN",
   "chapeta": "028",
   "cria": "",
   "material": "Estro Zoo + monta natural",
   "raza": "Eclipse y Timoteo",
   "fecha": "2026-08-06",
   "resultado": "PENDIENTE",
   "fechaConfirmacion": ""
  },
  {
   "tipo": "MN",
   "chapeta": "024",
   "cria": "",
   "material": "Estro Zoo + monta natural",
   "raza": "Eclipse y Timoteo",
   "fecha": "2026-08-06",
   "resultado": "PENDIENTE",
   "fechaConfirmacion": ""
  },
  {
   "tipo": "MN",
   "chapeta": "029",
   "cria": "",
   "material": "Estro Zoo + monta natural",
   "raza": "Eclipse y Timoteo",
   "fecha": "2026-08-06",
   "resultado": "PENDIENTE",
   "fechaConfirmacion": ""
  }
 ],
 "prenez": [
  {
   "chapeta": "041",
   "fechaPrenez": "2024-11-11",
   "fechaProbParto": "2025-08-21",
   "observaciones": "Parto 2025-07-17 — Cría: Julio",
   "estado": "PARIDA"
  },
  {
   "chapeta": "043",
   "fechaPrenez": "2024-11-11",
   "fechaProbParto": "2025-08-21",
   "observaciones": "Parto 2025-05-27 — Cría: Carbón",
   "estado": "PARIDA"
  },
  {
   "chapeta": "051",
   "fechaPrenez": "2025-08-14",
   "fechaProbParto": "2026-05-24",
   "observaciones": "Parto 2026-05-05 — Cría: Vendido",
   "estado": "PARIDA"
  },
  {
   "chapeta": "052",
   "fechaPrenez": "2025-05-14",
   "fechaProbParto": "2026-02-21",
   "observaciones": "Parto 2026-07-03 — Cría: Princesa",
   "estado": "PARIDA"
  },
  {
   "chapeta": "053",
   "fechaPrenez": "2025-05-14",
   "fechaProbParto": "2026-02-21",
   "observaciones": "Fecha incierta | Parto 2026-05-20",
   "estado": "PARIDA"
  },
  {
   "chapeta": "054",
   "fechaPrenez": "2025-05-14",
   "fechaProbParto": "2026-02-21",
   "observaciones": "Parto 2026-04-25 — Cría: Abril",
   "estado": "PARIDA"
  },
  {
   "chapeta": "043",
   "fechaPrenez": "2025-11-30",
   "fechaProbParto": "2026-09-06",
   "observaciones": "Monta natural (toro)",
   "estado": "PREÑADA"
  },
  {
   "chapeta": "041",
   "fechaPrenez": "2025-11-30",
   "fechaProbParto": "2026-09-06",
   "observaciones": "Monta natural (toro)",
   "estado": "PREÑADA"
  },
  {
   "chapeta": "012",
   "fechaPrenez": "2026-02-14",
   "fechaProbParto": "2026-11-21",
   "observaciones": "Transferencia de embrión sexado",
   "estado": "PREÑADA"
  },
  {
   "chapeta": "044",
   "fechaPrenez": "2026-02-14",
   "fechaProbParto": "2026-11-21",
   "observaciones": "Transferencia de embrión sexado",
   "estado": "PREÑADA"
  },
  {
   "chapeta": "025",
   "fechaPrenez": "2026-02-14",
   "fechaProbParto": "2026-11-21",
   "observaciones": "Transferencia de embrión sexado",
   "estado": "PREÑADA"
  },
  {
   "chapeta": "023",
   "fechaPrenez": "2026-02-14",
   "fechaProbParto": "2026-11-21",
   "observaciones": "Transferencia de embrión sexado",
   "estado": "PREÑADA"
  },
  {
   "chapeta": "013",
   "fechaPrenez": "2026-02-14",
   "fechaProbParto": "2026-11-21",
   "observaciones": "Transferencia de embrión sexado",
   "estado": "PREÑADA"
  },
  {
   "chapeta": "007",
   "fechaPrenez": "2026-03-26",
   "fechaProbParto": "2026-12-31",
   "observaciones": "Inseminación — Nelore",
   "estado": "PREÑADA"
  },
  {
   "chapeta": "032",
   "fechaPrenez": "2026-03-26",
   "fechaProbParto": "2026-12-31",
   "observaciones": "Inseminación — Nelore",
   "estado": "PREÑADA"
  },
  {
   "chapeta": "008",
   "fechaPrenez": "2026-04-24",
   "fechaProbParto": "2027-01-29",
   "observaciones": "Monta natural (toro)",
   "estado": "PREÑADA"
  },
  {
   "chapeta": "039",
   "fechaPrenez": "2026-04-26",
   "fechaProbParto": "2027-01-31",
   "observaciones": "Monta natural (toro)",
   "estado": "PREÑADA"
  },
  {
   "chapeta": "046",
   "fechaPrenez": "2026-04-29",
   "fechaProbParto": "2027-02-03",
   "observaciones": "Monta natural (toro)",
   "estado": "PREÑADA"
  },
  {
   "chapeta": "006",
   "fechaPrenez": "2026-04-29",
   "fechaProbParto": "2027-02-03",
   "observaciones": "Transferencia de embrión sexado",
   "estado": "PREÑADA"
  },
  {
   "chapeta": "010",
   "fechaPrenez": "2026-04-29",
   "fechaProbParto": "2027-02-03",
   "observaciones": "Transferencia de embrión sexado",
   "estado": "PREÑADA"
  },
  {
   "chapeta": "031",
   "fechaPrenez": "2026-04-29",
   "fechaProbParto": "2027-02-03",
   "observaciones": "Transferencia de embrión sexado",
   "estado": "PREÑADA"
  },
  {
   "chapeta": "030",
   "fechaPrenez": "2026-04-29",
   "fechaProbParto": "2027-02-03",
   "observaciones": "Transferencia de embrión sexado",
   "estado": "PREÑADA"
  },
  {
   "chapeta": "040",
   "fechaPrenez": "2026-05-20",
   "fechaProbParto": "2027-02-24",
   "observaciones": "Monta natural (toro)",
   "estado": "PREÑADA"
  },
  {
   "chapeta": "015",
   "fechaPrenez": "2026-05-25",
   "fechaProbParto": "2027-03-01",
   "observaciones": "Monta natural (toro)",
   "estado": "PREÑADA"
  },
  {
   "chapeta": "036",
   "fechaPrenez": "2026-04-25",
   "fechaProbParto": "2027-01-30",
   "observaciones": "Monta natural (toro)",
   "estado": "PREÑADA"
  },
  {
   "chapeta": "055",
   "fechaPrenez": "2026-05-26",
   "fechaProbParto": "2027-03-02",
   "observaciones": "Monta natural (toro)",
   "estado": "PREÑADA"
  },
  {
   "chapeta": "054",
   "fechaPrenez": "2026-05-17",
   "fechaProbParto": "2027-02-21",
   "observaciones": "Monta natural (toro)",
   "estado": "PREÑADA"
  },
  {
   "chapeta": "038",
   "fechaPrenez": "2026-04-28",
   "fechaProbParto": "2027-02-02",
   "observaciones": "Monta natural (toro)",
   "estado": "PREÑADA"
  }
 ],
 "pesajes": [
  {
   "fecha": "2026-04-03",
   "nombre": "Eclipse",
   "peso": 435.0,
   "edadMeses": null,
   "observaciones": "Toro — 3 años"
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Aurora",
   "peso": 157.0,
   "edadMeses": 7.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Lolita",
   "peso": 154.0,
   "edadMeses": 10.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Karina",
   "peso": 141.0,
   "edadMeses": 7.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Brisa",
   "peso": 127.0,
   "edadMeses": 5.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Minerva",
   "peso": 124.0,
   "edadMeses": 7.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Paty",
   "peso": 123.0,
   "edadMeses": 4.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Helena",
   "peso": 117.0,
   "edadMeses": 5.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Alma",
   "peso": 116.0,
   "edadMeses": 5.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Calista",
   "peso": 113.0,
   "edadMeses": 5.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Reina",
   "peso": 111.0,
   "edadMeses": 4.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Monica",
   "peso": 110.0,
   "edadMeses": 5.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Casandra",
   "peso": 105.0,
   "edadMeses": 4.5,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Fortuna",
   "peso": 105.0,
   "edadMeses": 5.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Pepa",
   "peso": 102.0,
   "edadMeses": 6.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "India",
   "peso": 97.0,
   "edadMeses": 4.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Diana",
   "peso": 94.0,
   "edadMeses": 3.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Iris",
   "peso": 93.0,
   "edadMeses": 6.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Artemisa",
   "peso": 90.0,
   "edadMeses": 3.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Freya",
   "peso": 87.0,
   "edadMeses": 3.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Afrodita",
   "peso": 87.0,
   "edadMeses": 4.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Luna",
   "peso": 86.0,
   "edadMeses": 3.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Frida",
   "peso": 78.0,
   "edadMeses": 6.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Penélope",
   "peso": 72.0,
   "edadMeses": 3.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Mercurio",
   "peso": 58.0,
   "edadMeses": 2.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Maya",
   "peso": 57.0,
   "edadMeses": 3.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Odín",
   "peso": 52.0,
   "edadMeses": 2.0,
   "observaciones": ""
  },
  {
   "fecha": "2026-04-03",
   "nombre": "Capuchino",
   "peso": 43.0,
   "edadMeses": 1.0,
   "observaciones": ""
  }
 ],
 "eventos": [
  {
   "timestamp": "2026-04-11 12:48:29",
   "categoria": "VACA",
   "refId": "051",
   "tipo": "PREÑEZ",
   "fecha": "2025-08-15",
   "precio": null,
   "causa": "Fecha incierta"
  },
  {
   "timestamp": "2026-04-11 12:49:23",
   "categoria": "VACA",
   "refId": "052",
   "tipo": "PREÑEZ",
   "fecha": "2025-05-15",
   "precio": null,
   "causa": "Fecha incierta"
  },
  {
   "timestamp": "2026-04-11 12:49:57",
   "categoria": "VACA",
   "refId": "053",
   "tipo": "PREÑEZ",
   "fecha": "2025-05-15",
   "precio": null,
   "causa": "Fecha incierta"
  },
  {
   "timestamp": "2026-04-11 12:49:58",
   "categoria": "VACA",
   "refId": "053",
   "tipo": "PREÑEZ",
   "fecha": "2025-05-15",
   "precio": null,
   "causa": "Fecha incierta"
  },
  {
   "timestamp": "2026-04-11 12:50:34",
   "categoria": "VACA",
   "refId": "054",
   "tipo": "PREÑEZ",
   "fecha": "2025-05-15",
   "precio": null,
   "causa": "Fecha incierta"
  },
  {
   "timestamp": "2026-04-11 12:50:36",
   "categoria": "VACA",
   "refId": "054",
   "tipo": "PREÑEZ",
   "fecha": "2025-05-15",
   "precio": null,
   "causa": "Fecha incierta"
  },
  {
   "timestamp": "2026-04-11 12:51:56",
   "categoria": "TERNERO",
   "refId": "Victoria",
   "tipo": "FALLECIDO",
   "fecha": "2026-04-10",
   "precio": null,
   "causa": "Enfermedad"
  },
  {
   "timestamp": "2026-04-26 14:41:35",
   "categoria": "VACA",
   "refId": "012",
   "tipo": "PREÑEZ",
   "fecha": "2026-04-12",
   "precio": null,
   "causa": "Tranferencia de embrión"
  },
  {
   "timestamp": "2026-04-26 14:42:06",
   "categoria": "VACA",
   "refId": "044",
   "tipo": "PREÑEZ",
   "fecha": "2026-04-12",
   "precio": null,
   "causa": "Tranferencia de embrión"
  },
  {
   "timestamp": "2026-04-26 14:42:42",
   "categoria": "VACA",
   "refId": "025",
   "tipo": "PREÑEZ",
   "fecha": "2026-04-12",
   "precio": null,
   "causa": "Transferencia de embrión"
  },
  {
   "timestamp": "2026-04-26 14:43:03",
   "categoria": "VACA",
   "refId": "023",
   "tipo": "PREÑEZ",
   "fecha": "2026-04-12",
   "precio": null,
   "causa": "Transferencia de embrión"
  },
  {
   "timestamp": "2026-04-26 14:43:20",
   "categoria": "VACA",
   "refId": "027",
   "tipo": "PREÑEZ",
   "fecha": "2026-04-12",
   "precio": null,
   "causa": "Transferencia de embrión"
  },
  {
   "timestamp": "2026-04-26 14:43:37",
   "categoria": "VACA",
   "refId": "013",
   "tipo": "PREÑEZ",
   "fecha": "2026-04-12",
   "precio": null,
   "causa": "Transferencia de embrión"
  },
  {
   "timestamp": "2026-04-26 14:49:08",
   "categoria": "TERNERO",
   "refId": "Abril",
   "tipo": "NACIMIENTO",
   "fecha": "2026-04-25",
   "precio": null,
   "causa": "Madre: vaca 54"
  },
  {
   "timestamp": "2026-04-26 14:49:08",
   "categoria": "VACA",
   "refId": "054",
   "tipo": "PARTO",
   "fecha": "2026-04-25",
   "precio": null,
   "causa": "Abril"
  },
  {
   "timestamp": "2026-05-14 23:59:10",
   "categoria": "TERNERO",
   "refId": "Vendido",
   "tipo": "NACIMIENTO",
   "fecha": "2026-05-08",
   "precio": null,
   "causa": "Madre: vaca 51"
  },
  {
   "timestamp": "2026-05-15 00:00:16",
   "categoria": "TERNERO",
   "refId": "Vendido",
   "tipo": "VENDIDO",
   "fecha": "2026-05-08",
   "precio": 1800000.0,
   "causa": "Ganadero Munar"
  },
  {
   "timestamp": "2026-07-13 12:00:00",
   "categoria": "TERNERO",
   "refId": "Freya",
   "tipo": "CORRECCIÓN",
   "fecha": "",
   "precio": null,
   "causa": "Estaba registrada como fallecida; sigue viva"
  },
  {
   "timestamp": "2026-07-13 12:00:00",
   "categoria": "TERNERO",
   "refId": "Flora",
   "tipo": "FALLECIDO",
   "fecha": "2026-03-15",
   "precio": null,
   "causa": "Fecha aproximada (marzo 2026)"
  },
  {
   "timestamp": "2026-07-13 12:00:00",
   "categoria": "VACA",
   "refId": "055",
   "tipo": "ALTA_VACA",
   "fecha": "",
   "precio": null,
   "causa": "5.º viaje"
  },
  {
   "timestamp": "2026-07-13 12:00:00",
   "categoria": "VACA",
   "refId": "056",
   "tipo": "ALTA_VACA",
   "fecha": "",
   "precio": null,
   "causa": "5.º viaje"
  },
  {
   "timestamp": "2026-07-13 12:00:00",
   "categoria": "VACA",
   "refId": "057",
   "tipo": "ALTA_VACA",
   "fecha": "",
   "precio": null,
   "causa": "5.º viaje"
  },
  {
   "timestamp": "2026-07-13 12:00:00",
   "categoria": "VACA",
   "refId": "058",
   "tipo": "ALTA_VACA",
   "fecha": "",
   "precio": null,
   "causa": "Nueva"
  },
  {
   "timestamp": "2026-07-13 12:00:00",
   "categoria": "VACA",
   "refId": "059",
   "tipo": "ALTA_VACA",
   "fecha": "",
   "precio": null,
   "causa": "Nueva"
  },
  {
   "timestamp": "2026-07-13 12:00:00",
   "categoria": "VACA",
   "refId": "060",
   "tipo": "ALTA_VACA",
   "fecha": "",
   "precio": null,
   "causa": "Nueva"
  },
  {
   "timestamp": "2026-07-13 12:00:00",
   "categoria": "TERNERO",
   "refId": "Jennifer",
   "tipo": "NACIMIENTO",
   "fecha": "2026-05-22",
   "precio": null,
   "causa": "Madre: vaca 057"
  },
  {
   "timestamp": "2026-07-13 12:30:00",
   "categoria": "TERNERO",
   "refId": "Brisa",
   "tipo": "FALLECIDO",
   "fecha": "2026-05-20",
   "precio": null,
   "causa": ""
  },
  {
   "timestamp": "2026-07-13 13:00:00",
   "categoria": "VACA",
   "refId": "051",
   "tipo": "PARTO",
   "fecha": "2026-05-05",
   "precio": null,
   "causa": "Ternero macho vendido al nacer"
  },
  {
   "timestamp": "2026-07-13 13:00:00",
   "categoria": "VACA",
   "refId": "047",
   "tipo": "PARTO",
   "fecha": "2026-03-17",
   "precio": null,
   "causa": "Ternero nació enfermo y murió"
  },
  {
   "timestamp": "2026-07-13 13:00:00",
   "categoria": "VACA",
   "refId": "048",
   "tipo": "PARTO",
   "fecha": "2026-03-15",
   "precio": null,
   "causa": "Ternero nació enfermo y murió"
  },
  {
   "timestamp": "2026-07-13 13:00:00",
   "categoria": "VACA",
   "refId": "053",
   "tipo": "PARTO",
   "fecha": "2026-05-20",
   "precio": null,
   "causa": "Ternero muerto"
  },
  {
   "timestamp": "2026-07-13 13:00:00",
   "categoria": "VACA",
   "refId": "042",
   "tipo": "PREÑEZ",
   "fecha": "2026-05-13",
   "precio": null,
   "causa": "Monta natural (toro)"
  },
  {
   "timestamp": "2026-07-13 13:00:00",
   "categoria": "SANIDAD",
   "refId": "Toda la lechería",
   "tipo": "TRATAMIENTO",
   "fecha": "2026-06-20",
   "precio": null,
   "causa": "Hemopar + Impulsor FE — reaplicar en 45 días"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "VACA",
   "refId": "052",
   "tipo": "PARTO",
   "fecha": "2026-07-03",
   "precio": null,
   "causa": "Princesa"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "TERNERO",
   "refId": "Princesa",
   "tipo": "NACIMIENTO",
   "fecha": "2026-07-03",
   "precio": null,
   "causa": "Madre: vaca 052"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "VACA",
   "refId": "027",
   "tipo": "PÉRDIDA",
   "fecha": "2026-07-21",
   "precio": null,
   "causa": "Perdió la cría — preñez cerrada"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "VACA",
   "refId": "043",
   "tipo": "PREÑEZ",
   "fecha": "2025-11-30",
   "precio": null,
   "causa": "Monta natural (toro)"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "VACA",
   "refId": "041",
   "tipo": "PREÑEZ",
   "fecha": "2025-11-30",
   "precio": null,
   "causa": "Monta natural (toro)"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "VACA",
   "refId": "012",
   "tipo": "PREÑEZ",
   "fecha": "2026-02-14",
   "precio": null,
   "causa": "Transferencia de embrión sexado"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "VACA",
   "refId": "044",
   "tipo": "PREÑEZ",
   "fecha": "2026-02-14",
   "precio": null,
   "causa": "Transferencia de embrión sexado"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "VACA",
   "refId": "025",
   "tipo": "PREÑEZ",
   "fecha": "2026-02-14",
   "precio": null,
   "causa": "Transferencia de embrión sexado"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "VACA",
   "refId": "023",
   "tipo": "PREÑEZ",
   "fecha": "2026-02-14",
   "precio": null,
   "causa": "Transferencia de embrión sexado"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "VACA",
   "refId": "013",
   "tipo": "PREÑEZ",
   "fecha": "2026-02-14",
   "precio": null,
   "causa": "Transferencia de embrión sexado"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "VACA",
   "refId": "007",
   "tipo": "PREÑEZ",
   "fecha": "2026-03-26",
   "precio": null,
   "causa": "Inseminación — Nelore"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "VACA",
   "refId": "032",
   "tipo": "PREÑEZ",
   "fecha": "2026-03-26",
   "precio": null,
   "causa": "Inseminación — Nelore"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "VACA",
   "refId": "008",
   "tipo": "PREÑEZ",
   "fecha": "2026-04-24",
   "precio": null,
   "causa": "Monta natural (toro)"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "VACA",
   "refId": "039",
   "tipo": "PREÑEZ",
   "fecha": "2026-04-26",
   "precio": null,
   "causa": "Monta natural (toro)"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "VACA",
   "refId": "046",
   "tipo": "PREÑEZ",
   "fecha": "2026-04-29",
   "precio": null,
   "causa": "Monta natural (toro)"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "VACA",
   "refId": "006",
   "tipo": "PREÑEZ",
   "fecha": "2026-04-29",
   "precio": null,
   "causa": "Transferencia de embrión sexado"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "VACA",
   "refId": "010",
   "tipo": "PREÑEZ",
   "fecha": "2026-04-29",
   "precio": null,
   "causa": "Transferencia de embrión sexado"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "VACA",
   "refId": "031",
   "tipo": "PREÑEZ",
   "fecha": "2026-04-29",
   "precio": null,
   "causa": "Transferencia de embrión sexado"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "VACA",
   "refId": "030",
   "tipo": "PREÑEZ",
   "fecha": "2026-04-29",
   "precio": null,
   "causa": "Transferencia de embrión sexado"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "VACA",
   "refId": "040",
   "tipo": "PREÑEZ",
   "fecha": "2026-05-20",
   "precio": null,
   "causa": "Monta natural (toro)"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "VACA",
   "refId": "042",
   "tipo": "TRANSFERENCIA",
   "fecha": "2026-07-17",
   "precio": null,
   "causa": "Embrión sexado — pendiente por confirmar"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "VACA",
   "refId": "022",
   "tipo": "TRANSFERENCIA",
   "fecha": "2026-07-17",
   "precio": null,
   "causa": "Embrión sexado — pendiente por confirmar"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "VACA",
   "refId": "035",
   "tipo": "TRANSFERENCIA",
   "fecha": "2026-07-17",
   "precio": null,
   "causa": "Embrión sexado — pendiente por confirmar"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "VACA",
   "refId": "060",
   "tipo": "TRANSFERENCIA",
   "fecha": "2026-07-17",
   "precio": null,
   "causa": "Embrión sexado — pendiente por confirmar"
  },
  {
   "timestamp": "2026-07-21 09:00:00",
   "categoria": "VACA",
   "refId": "057",
   "tipo": "TRANSFERENCIA",
   "fecha": "2026-07-17",
   "precio": null,
   "causa": "Embrión sexado — pendiente por confirmar"
  },
  {
   "timestamp": "2026-07-21 10:00:00",
   "categoria": "VACA",
   "refId": "015",
   "tipo": "PREÑEZ",
   "fecha": "2026-05-25",
   "precio": null,
   "causa": "Monta natural (toro)"
  },
  {
   "timestamp": "2026-07-21 10:00:00",
   "categoria": "VACA",
   "refId": "036",
   "tipo": "PREÑEZ",
   "fecha": "2026-04-25",
   "precio": null,
   "causa": "Monta natural (toro)"
  },
  {
   "timestamp": "2026-07-21 10:00:00",
   "categoria": "VACA",
   "refId": "055",
   "tipo": "PREÑEZ",
   "fecha": "2026-05-26",
   "precio": null,
   "causa": "Monta natural (toro)"
  },
  {
   "timestamp": "2026-07-21 10:00:00",
   "categoria": "VACA",
   "refId": "054",
   "tipo": "PREÑEZ",
   "fecha": "2026-05-17",
   "precio": null,
   "causa": "Monta natural (toro)"
  },
  {
   "timestamp": "2026-07-21 10:00:00",
   "categoria": "VACA",
   "refId": "038",
   "tipo": "PREÑEZ",
   "fecha": "2026-04-28",
   "precio": null,
   "causa": "Monta natural (toro)"
  },
  {
   "timestamp": "2026-08-09 09:00:00",
   "categoria": "TORO",
   "refId": "Eclipse",
   "tipo": "ALTA_TORO",
   "fecha": "2023-01-02",
   "precio": null,
   "causa": "Toro reproductor"
  },
  {
   "timestamp": "2026-08-09 09:00:00",
   "categoria": "TORO",
   "refId": "Timoteo",
   "tipo": "ALTA_TORO",
   "fecha": "2023-03-17",
   "precio": null,
   "causa": "Toro reproductor"
  },
  {
   "timestamp": "2026-08-09 09:00:00",
   "categoria": "VACA",
   "refId": "017",
   "tipo": "MONTA",
   "fecha": "2026-08-06",
   "precio": null,
   "causa": "Estro Zoo — toros Eclipse y Timoteo"
  },
  {
   "timestamp": "2026-08-09 09:00:00",
   "categoria": "VACA",
   "refId": "014",
   "tipo": "MONTA",
   "fecha": "2026-08-06",
   "precio": null,
   "causa": "Estro Zoo — toros Eclipse y Timoteo"
  },
  {
   "timestamp": "2026-08-09 09:00:00",
   "categoria": "VACA",
   "refId": "037",
   "tipo": "MONTA",
   "fecha": "2026-08-06",
   "precio": null,
   "causa": "Estro Zoo — toros Eclipse y Timoteo"
  },
  {
   "timestamp": "2026-08-09 09:00:00",
   "categoria": "VACA",
   "refId": "018",
   "tipo": "MONTA",
   "fecha": "2026-08-06",
   "precio": null,
   "causa": "Estro Zoo — toros Eclipse y Timoteo"
  },
  {
   "timestamp": "2026-08-09 09:00:00",
   "categoria": "VACA",
   "refId": "028",
   "tipo": "MONTA",
   "fecha": "2026-08-06",
   "precio": null,
   "causa": "Estro Zoo — toros Eclipse y Timoteo"
  },
  {
   "timestamp": "2026-08-09 09:00:00",
   "categoria": "VACA",
   "refId": "024",
   "tipo": "MONTA",
   "fecha": "2026-08-06",
   "precio": null,
   "causa": "Estro Zoo — toros Eclipse y Timoteo"
  },
  {
   "timestamp": "2026-08-09 09:00:00",
   "categoria": "VACA",
   "refId": "029",
   "tipo": "MONTA",
   "fecha": "2026-08-06",
   "precio": null,
   "causa": "Estro Zoo — toros Eclipse y Timoteo"
  }
 ],
 "tratamientos": [
  {
   "fecha": "2026-06-20",
   "producto": "Hemopar + Impulsor FE",
   "aplicadoA": "Toda la lechería",
   "diasReaplicar": 45,
   "fechaReaplicar": "2026-08-04",
   "estado": "PENDIENTE",
   "notas": ""
  }
 ]
};
